### ISSUE TITLE
Luakit with Home Assistant - not all dashboard features available

### ISSUE THREAD

**Issue by taucher4000** [luakit/luakit#1114]
**Current Behavior:**
I'm using luakit on my Home Assistant  as an add-on using [HAOS-kiosk](https://github.com/puterboy/HAOS-kiosk) . This is running on a Raspberry Pi 4 with a 5 Inch DSI Touch display connected to. Luakit in general is working fine and I can control the Dashboard. However, some dashboard elements, especially the new Home Assistant Custom Features (https://developers.home-assistant.io/docs/frontend/custom-ui/custom-card-feature/) are not working. I'm not able to touch on the elements. The same elements on e regular browser on my laptop are working just fine.

**Desired Behavior:**
Looks like not all the javaScript custom Element interactions are working with luakit

**How can we reproduce it (step by step):**

For the dashboard, I'm using the "Custom card feature" which HA just announced (https://developers.home-assistant.io/docs/frontend/custom-ui/custom-card-feature/). I'm using [this](https://github.com/Nerwyn/custom-card-features) HACS extension. The extension is working fine and and I'm able to create custom components like toggle or sliders (see screenshot). Unfortunately, all the custom card components are not controllable in HAOS-Kiosk (but working fine on the Desktop computer). They are visible but not clickable. All other standard card elements in the dashboard are working just fine. Only the custom card features are not working. 

My assumption is that something is either wrong with luakit or a configuration is missing.

![Image](https://github.com/user-attachments/assets/35f0c3b1-43db-406b-a682-ddb626af94e7)

The card is created like the following:

```
features:
  - type: custom:service-call
    entries:
      - type: spinbox
        entity_id: input_number.test
        range:
          - 0
          - 100
        tap_action:
          action: perform-action
          target:
            entity_id: input_number.test
          perform_action: counter.increment
          data: {}
        step: 1
        label: "{{value}}"
type: tile
entity: input_number.test
features_position: inline
vertical: false
```

**Environment:**

```
/ # luakit -V
luakit a7e0cdda
  built with: webkit 2.46.3 (installed version: 2.46.3)
                 GTK 3.24.43 
                GLIB 2.82.2 
                SOUP 3.6.0 
```

Raspberry Pi with Home Assistant 2025.5.2 and https://github.com/puterboy/HAOS-kiosk add-on

**Note about webkit issues:**

If you're reporting a rendering issue, please test it with the gnome
browser ephiphany as well. If the issue occurs there too, we're very
likely not able to help. These issues should be reported to webkit:
https://bugs.webkit.org
