### ISSUE TITLE
Make flatpak

### ISSUE THREAD

**Issue by schvabodka-man** [luakit/luakit#451]
Hi! That would be nice if you'll make flatpak for app because right now installation is a little bit hard.

**Comment by aidanholm** [comment]
Hi! Should be doable, perhaps after the next release I'll take a look

 I'm also happy to help with installation problems, and there's always `#luakit` on OFTC if you need help :)

**Comment by schvabodka-man** [comment]
The problem is mostly with lua 5.1 and lua-fs package. Actually i installed it alright but in some distros there might not be luarocks for 5.1 or lua 5.1 at all

**Comment by curioussavage** [comment]
I would vote for an AppImage instead. Looked into doing it myself but I am just starting to dabble in native app development so I am just about useless!

**Comment by schvabodka-man** [comment]
AppImage doesn't have centralized repos plus flatpak is really more hassle free

**Comment by aidanholm** [comment]
AFAIK, an AppImage is effectively just an executable file coupled with a mountable filesystem with all requirements. The major concern is being forced to respond to critical updates to webkit2gtk; any AppImage packager will have to dedicate themselves to releasing new updates promptly. 

Flatpak has a whole bunch more features, which as the developer (not packager) doesn't really concern me, except for the fact that at least one runtime includes webkit2gtk, which nullifies the security updates concern. For this reason, I'm more inclined to go with Flatpak.

**Comment by curioussavage** [comment]
> flatpak is really more hassle free

For developer/packager or for users? Last time I looked into it flatpack requires you install their software before you can install any apps.

That said I would love it if luakit was offered in any form that is easier to install than compiling!

**Comment by schvabodka-man** [comment]
For users.

**Comment by curioussavage** [comment]
I decided to give this a try since I've been working with flatpak a little recently.

I tried with this manifest (disclaimer: I don't know what I"m doing)

```json
{
    "app-id": "org.gnome.luakit",
    "runtime": "org.gnome.Platform",
    "runtime-version": "3.28",
    "sdk": "org.gnome.Sdk",
    "command": "luakit",
    "finish-args": [
        "--share=network",
        "--share=ipc",
        "--socket=x11",
        "--socket=wayland",
        "--filesystem=xdg-run/dconf",
        "--filesystem=~/.config/dconf:ro",
        "--talk-name=ca.desrt.dconf",
        "--env=DCONF_USER_CONFIG_DIR=.config/dconf"
    ],
    "build-options": {
    },
    "cleanup": [
        "/include",
        "/lib/pkgconfig",
        "/man",
        "/share/doc",
        "/share/gtk-doc",
        "/share/man",
        "/share/pkgconfig",
        "*.la",
        "*.a"
    ],
    "modules": [
    	{
            "name":"lua5.1",
            "no-autogen": true,
    	    "sources": [
	    	{
    	            "type": "archive",
    	            "url": "https://www.lua.org/ftp/lua-5.1.5.tar.gz",
    	            "sha1": "b3882111ad02ecc6b972f8c1241647905cb2e3fc"
    	        },
                {
                "type": "shell",
                "commands": [ "PREFIX=${FLATPAK_DEST} make linux install" ]
                }
    	    ]
    	},
        {
            "name": "luakit",
            "builddir": true,
            "buildsystem": "simple",
            "build-commands": [
                "make PREFIX=${FLATPAK_DEST} install"
            ],
            "sources": [
                {
                    "type": "archive",
                    "url": "https://github.com/luakit/luakit/archive/2.1.tar.gz",
                    "sha256": "ecbfa23316712f444714387b2ffd846626dab6e40b444d3def4475c145d56f26"
                }
            ]
        }
    ]
}
```
so with this one it compiles lua but then fails with this:
```
make[2]: Leaving directory '/home/awinn/projects/luakit/.flatpak-builder/build/lua5.1-11/src'
make[1]: Leaving directory '/home/awinn/projects/luakit/.flatpak-builder/build/lua5.1-11/src'
cd src && mkdir -p /usr/local/bin /usr/local/include /usr/local/lib /usr/local/man/man1 /usr/local/share/lua/5.1 /usr/local/lib/lua/5.1
mkdir: cannot create directory ‘/usr/local’: Read-only file system
mkdir: cannot create directory ‘/usr/local’: Read-only file system
mkdir: cannot create directory ‘/usr/local’: Read-only file system
mkdir: cannot create directory ‘/usr/local’: Read-only file system
mkdir: cannot create directory ‘/usr/local’: Read-only file system
mkdir: cannot create directory ‘/usr/local’: Read-only file system
```

**Comment by curioussavage** [comment]
With the following manifest using a flatpak module for luajit I get into compiling luakit and it fails when lfs is not there. Not surprising but I haven't tried including an lfs module because some of the documentation here says you have to build it with lua5.1 but I couldn't get 5.1 to work.

```json
{
    "app-id": "org.gnome.luakit",
    "runtime": "org.gnome.Platform",
    "runtime-version": "3.28",
    "sdk": "org.gnome.Sdk",
    "command": "luakit",
    "finish-args": [
        "--share=network",
        "--share=ipc",
        "--socket=x11",
        "--socket=wayland",
        "--filesystem=xdg-run/dconf",
        "--filesystem=~/.config/dconf:ro",
        "--talk-name=ca.desrt.dconf",
        "--env=DCONF_USER_CONFIG_DIR=.config/dconf"
    ],
    "build-options": {
    },
    "cleanup": [
        "/include",
        "/lib/pkgconfig",
        "/man",
        "/share/doc",
        "/share/gtk-doc",
        "/share/man",
        "/share/pkgconfig",
        "*.la",
        "*.a"
    ],
    "modules": [
        {
            "name": "luajit",
            "no-autogen": true,
            "cleanup": [ "/lib/*.a", "/include" ],
            "sources": [
                {
                "type": "archive",
                "url": "http://luajit.org/download/LuaJIT-2.0.5.tar.gz",
                "sha256": "874b1f8297c697821f561f9b73b57ffd419ed8f4278c82e05b48806d30c1e979"
                },
                {
                "type": "shell",
                "commands": [ "sed -i 's|/usr/local|/app|' ./Makefile" ]
                }
            ]
        },
        {
            "name": "luakit",
            "builddir": true,
            "buildsystem": "simple",
            "build-commands": [
                "make PREFIX=${FLATPAK_DEST} install"
            ],
            "sources": [
                {
                    "type": "archive",
                    "url": "https://github.com/luakit/luakit/archive/2.1.tar.gz",
                    "sha256": "ecbfa23316712f444714387b2ffd846626dab6e40b444d3def4475c145d56f26"
                }
            ]
        }
    ]
}
```

edit: oh sorry I see that the lfs documentation is where it says it should be built with 5.1

**Comment by curioussavage** [comment]
I'll just add too that there is a ready to go module for lua 5.3 so If luakit could be built with that then we would be good to go.

**Comment by curioussavage** [comment]
On the off chance It would work I just copied in lfs from my host system and made a module to copy it somewhere it would be found. Got the following:
```
luajit: error loading module 'lfs' from file '/app/lib/lua/5.1/lfs.so':
	/lib/libc.so.6: version `GLIBC_2.28' not found (required by /app/lib/lua/5.1/lfs.so)
```

**Comment by BakedSnake** [comment]
So this was as far as I got:
```
app-id: com.gnome.luakit
runtime: org.gnome.Platform
runtime-version: '42'
sdk: org.gnome.Sdk
command: luakit
finish-args:
  --share=network,
  --share=ipc,
  --socket=x11,
  --socket=wayland,
  --filesystem=xdg-run/dconf,
  --filesystem=~/.config/dconf:ro,
  --talk-name=ca.desrt.dconf,
  --env=DCONF_USER_CONFIG_DIR=.config/dconf
modules:
  - name: lua5.4.4
    no-autogen: true
    sources:
      - type: archive
        url: https://www.lua.org/ftp/lua-5.4.4.tar.gz
        sha256: 164c7849653b80ae67bec4b7473b884bf5cc8d2dca05653475ec2ed27b9ebf61
      - type: shell
        commands:
          - sed -i 's|/usr/local|/app|' ./Makefile
  - name: luajit
    no-autogen: true
    cleanup:
      - /bin
      - /include
      - /lib/pkgconfig
      - /share/man
    sources:
      - type: archive
        url: https://luajit.org/download/LuaJIT-2.0.5.tar.gz
        sha256: 874b1f8297c697821f561f9b73b57ffd419ed8f4278c82e05b48806d30c1e979
      - type: shell
        commands:
          - sed -i 's|/usr/local|/app|' ./Makefile
  - name: luafilessystem
    no-autogen: true
    sources:
      - type: git
        url: https://github.com/lunarmodules/luafilesystem.git
      - type: shell
        commands:
          - sed -i 's|/usr/local|/app|' ./config
  - name: luakit
    builddir: true
    no-autogen: true
    sources:
      - type: git
        url: https://github.com/luakit/luakit.git
      - type: shell
        commands:
          #- sed -i 's|/usr/local|/app|' ./config.mk
          make PREFIX=/app install
```

But i get this when compiling luakit:
```
extension/clib/page.c: In function ‘luaH_page_wrap_js’:
extension/clib/page.c:184:5: warning: ‘webkit_frame_get_javascript_context_for_script_world’ is deprecated: Use 'webkit_frame_get_js_context_for_script_world' instead [-Wdeprecated-declarations]
  184 |     JSGlobalContextRef ctx = webkit_frame_get_javascript_context_for_script_world(frame, world);
      |     ^~~~~~~~~~~~~~~~~~
In file included from /usr/include/webkitgtk-4.0/webkit2/webkit-web-extension.h:33,
                 from ./extension/extension.h:26,
                 from extension/clib/page.c:19:
/usr/include/webkitgtk-4.0/webkit2/WebKitFrame.h:74:1: note: declared here
   74 | webkit_frame_get_javascript_context_for_script_world     (WebKitFrame       *frame,
      | ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Error: module luakit: Child process exited with code 2
```

any ideas?

**Comment by BakedSnake** [comment]
I got it to work like this:
```
app-id: org.gnome.luakit
runtime: org.gnome.Platform
runtime-version: '3.34'
sdk: org.gnome.Sdk
command: luakit
finish-args:
  - --share=network
  - --share=ipc
  - --device=dri
  - --socket=x11
  - --socket=pulseaudio
  - --filesystem=xdg-config:rw
  - --filesystem=xdg-cache:rw
  - --filesystem=xdg-data:rw
  - --talk-name=org.gtk.vfs.*
  - --filesystem=xdg-run/gvfsd
  - --filesystem=xdg-run/dconf
  - --filesystem=~/.config/dconf:ro
  - --talk-name=ca.desrt.dconf
  - --env=DCONF_USER_CONFIG_DIR=.config/dconf
modules:
  - name: lua5.1
    no-autogen: true
    buildsystem: simple
    build-commands:
      - make linux install
    sources:
      - type: archive
        url: https://www.lua.org/ftp/lua-5.1.tar.gz
        sha256: 7f5bb9061eb3b9ba1e406a5aa68001a66cb82bac95748839dc02dd10048472c1
      - type: shell
        commands:
          - sed -i 's|/usr/local|/app|' ./Makefile
  - name: luajit
    no-autogen: true
    cleanup:
      - /bin
      - /include
      - /lib/pkgconfig
      - /share/man
    sources:
      - type: archive
        url: https://luajit.org/download/LuaJIT-2.0.5.tar.gz
        sha256: 874b1f8297c697821f561f9b73b57ffd419ed8f4278c82e05b48806d30c1e979
      - type: shell
        commands:
          - sed -i 's|/usr/local|/app|' ./Makefile
  - name: luafilesystem
    no-autogen: true
    sources:
      - type: git
        url: https://github.com/lunarmodules/luafilesystem.git
      - type: shell
        commands:
          - sed -i 's|/usr/local|/app|' ./config
  - name: luakit
    builddir: true
    buildsystem: simple
    build-commands:
      -  LIBGL_DRI3_DISABLE=1 WEBKIT_USE_SINGLE_WEB_PROCESS=1 make install
    no-autogen: true
    sources:
      - type: git
        url: https://github.com/luakit/luakit.git
        branch: 2.2
      - type: shell
        commands:
          - sed -i 's|/usr/local|/app|' ./config.mk
          - sed -i 's|/etc/xdg|/app/etc/xdg|' ./config.mk
```

Using runtime version 3.34 because 42 and 40 were having issues displaying webpages like github. Possibly a webkit-gtk issue.
